name: test

on:
  workflow_dispatch: 
  pull_request:
    branches: [main]
    paths: 
    - '.github/workflows/test.yml'

jobs: 
  test1: 
    runs-on: ubuntu-latest

    steps: 
    - uses: actions/checkout@v4.2.1